name: Build Release

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          cd client && npm install --production && npm run build
          cd .. && mv client/build ./build
          rm -rf client && mkdir client && mv ./build client/
          tar zcvf release.tar.gz *
      - name: Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
