name: Build Release

on: create

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          cd client && npm install --production && npm run build
          cd .. && mv client/build ./build
          rm -rf client && mkdir client && mv ./build client/
          tar zcvf release.tar.gz *
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.gz
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
